version: '3.5'

services:
# Traefik is a reverse-proxy that allows you to match "localhost:8080" to any domain name, as long as it targets your server's ip.
  traefik:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - 8080
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      ############################################
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.docker.networks=default"
      - "traefik.frontend.entryPoints=http,https"
# Portainer is a really nice GUI for Docker, even though I still prefer type commands on my console
  portainer:
    image: portainer/portainer:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    labels:
      ############################################
      - "traefik.port=9000"
      - "traefik.docker.networks=default"
      - "traefik.protocol=http"
# Working on it
  jenkins:
    image: jenkins/jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - "/data/jenkins:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      ############################################
# Imagine Github. Now imagine Gitlab. Now imagine it on your own server. Exactly.
  gogs:
    image: gogs/gogs
    ports:
      - "3000:3000"
      - "10022:22"
    volumes:
      - "/var/gogs:/data"
    labels:
      - "traefik.docker.networks=default"
      - "traefik.port=3000"
      ############################################
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=gogs
      - MYSQL_USER=gogs
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    labels:
      - "traefik.backend=MariaDB"
    networks:
      - default

volumes:
  portainerdata:

networks:
  default:
    external:
      name: josephlevarato
